### Troubleshooting the Time-step Issue in MtHop Canopy

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import pysumma as ps
import copy
import os.path

from pysumma.plotting import plotting
from jupyterthemes import jtplot

import pandas as pd
import numpy as np
import xarray as xr

In [3]:
!pwd

/home/jovyan/work/cewa564_project/olympics/mthop/notebooks


#### Investigating the Local Attributes File First

In [5]:
local_a = xr.open_dataset('/home/jovyan/work/cewa564_project/olympics/mthop/summa_setup/params/local_attributes.nc')
local_a

<xarray.Dataset>
Dimensions:         (gru: 1, hru: 1)
Dimensions without coordinates: gru, hru
Data variables:
    hruId           (hru) int32 ...
    gruId           (gru) int32 ...
    hru2gruId       (hru) int32 ...
    downHRUindex    (hru) int32 ...
    longitude       (hru) float64 ...
    latitude        (hru) float64 ...
    elevation       (hru) float64 ...
    HRUarea         (hru) float64 ...
    tan_slope       (hru) float64 ...
    contourLength   (hru) float64 ...
    slopeTypeIndex  (hru) int32 ...
    soilTypeIndex   (hru) int32 ...
    vegTypeIndex    (hru) int32 ...
    mHeight         (hru) float64 ...
Attributes:
    history:  Converted to NetCDF using "../../tools/localAttributes_ascii_to...

In [9]:
local_a.hru2gruId

<xarray.DataArray 'hru2gruId' (hru: 1)>
array([1001], dtype=int32)
Dimensions without coordinates: hru
Attributes:
    long_name:  Index of GRU to which the HRU belongs
    units:      -

In [10]:
local_a.gruId

<xarray.DataArray 'gruId' (gru: 1)>
array([1001], dtype=int32)
Dimensions without coordinates: gru
Attributes:
    long_name:  Index of grouped response unit (GRU)
    units:      -
    v_type:     scalarv

In [11]:
local_a.hruId

<xarray.DataArray 'hruId' (hru: 1)>
array([1001], dtype=int32)
Dimensions without coordinates: hru
Attributes:
    long_name:  Index of hydrological response unit (HRU)
    units:      -
    v_type:     scalarv

#### Investigating the Forcing Data, looking for date/time step Issues

In [14]:
forcing = xr.open_dataset('/home/jovyan/work/cewa564_project/olympics/mthop/summa_setup/forcings/MtHopper_2016_filled.nc')
forcing

<xarray.Dataset>
Dimensions:    (hru: 1, time: 7177)
Coordinates:
  * time       (time) datetime64[ns] 2015-10-01 ... 2016-07-26
Dimensions without coordinates: hru
Data variables:
    LWRadAtm   (time, hru) float64 ...
    SWRadAtm   (time, hru) float64 ...
    airtemp    (time, hru) float64 ...
    pptrate    (time, hru) float64 ...
    spechum    (time, hru) float64 ...
    airpres    (time, hru) float64 ...
    windspd    (time, hru) float64 ...
    datastep   float64 ...
    latitude   (hru) float64 ...
    longitude  (hru) float64 ...
    hruID      (hru) float64 ...
    hruId      (hru) float64 ...
    data_step  float64 ...

In [15]:
forcing.data_step

<xarray.DataArray 'data_step' ()>
array(3600.)

In [16]:
forcing.datastep

<xarray.DataArray 'datastep' ()>
array(9.96921e+36)

In [17]:
forcing.hruID

<xarray.DataArray 'hruID' (hru: 1)>
array([9.96921e+36])
Dimensions without coordinates: hru

In [18]:
forcing.hruId

<xarray.DataArray 'hruId' (hru: 1)>
array([1001.])
Dimensions without coordinates: hru

### Going to look into the CUES site data and see if the date time/ HRUid/ etc are all the same... 

In [19]:
!pwd

/home/jovyan/work/cewa564_project/olympics/mthop/notebooks


In [20]:
cues_forcing = xr.open_dataset('/home/jovyan/cues/summa_setup/forcings/cues2016.nc')
cues_forcing

<xarray.Dataset>
Dimensions:    (hru: 1, time: 8784)
Coordinates:
  * time       (time) datetime64[ns] 2016-01-01T01:00:00 ... 2017-01-01
Dimensions without coordinates: hru
Data variables:
    airpres    (time, hru) float64 ...
    spechum    (time, hru) float64 ...
    windspd    (time, hru) float64 ...
    airtemp    (time, hru) float64 ...
    SWRadAtm   (time, hru) float64 ...
    LWRadAtm   (time, hru) float64 ...
    pptrate    (time, hru) float64 ...
    latitude   (hru) float64 ...
    longitude  (hru) float64 ...
    data_step  float64 ...
    hruId      (hru) int32 ...