#### Notebook to get local attribute files matching the forcing data

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pysumma as ps
import copy
import os.path

from pysumma.plotting import plotting
from jupyterthemes import jtplot

import pandas as pd
import numpy as np
import xarray as xr

In [2]:
!pwd

/home/jovyan/work/cewa564_project/niwot/notebooks


#### Local Attributes File

In [3]:
local_a = xr.open_dataset('/home/jovyan/work/cewa564_project/niwot/summa_setup/params/local_attributes.nc')
local_a

<xarray.Dataset>
Dimensions:         (gru: 1, hru: 1)
Dimensions without coordinates: gru, hru
Data variables:
    hruId           (hru) int32 ...
    gruId           (gru) int32 ...
    hru2gruId       (hru) int32 ...
    downHRUindex    (hru) int32 ...
    longitude       (hru) float64 ...
    latitude        (hru) float64 ...
    elevation       (hru) float64 ...
    HRUarea         (hru) float64 ...
    tan_slope       (hru) float64 ...
    contourLength   (hru) float64 ...
    slopeTypeIndex  (hru) int32 ...
    soilTypeIndex   (hru) int32 ...
    vegTypeIndex    (hru) int32 ...
    mHeight         (hru) float64 ...
Attributes:
    history:  Converted to NetCDF using "../../tools/localAttributes_ascii_to...

In [ ]:
# Niwot Site Specifics that need to be changed in the attribute file
# latitude 40.0329
# longitude -105.5464
# elevation 3050 m

In [16]:
local_a['latitude'][:] = 40.0329
local_a['latitude']

<xarray.DataArray 'latitude' (hru: 1)>
array([40.0329])
Dimensions without coordinates: hru
Attributes:
    long_name:  Latitude of HRU's centroid
    units:      Decimal degree north

In [17]:
local_a['longitude'][:] = -105.5464
local_a['elevation'][:] = 3050

In [19]:
local_a.hruId

<xarray.DataArray 'hruId' (hru: 1)>
array([1001], dtype=int32)
Dimensions without coordinates: hru
Attributes:
    long_name:  Index of hydrological response unit (HRU)
    units:      -
    v_type:     scalarv

### Focing Data

In [6]:
forcing = xr.open_dataset('/home/jovyan/work/cewa564_project/niwot/summa_setup/forcings/Niwot_2016.nc')
forcing

<xarray.Dataset>
Dimensions:    (hru: 1, time: 8784)
Coordinates:
  * time       (time) datetime64[ns] 2015-10-01 ... 2016-09-30T23:00:00
Dimensions without coordinates: hru
Data variables:
    LWRadAtm   (time, hru) float64 ...
    SWRadAtm   (time, hru) float64 ...
    airtemp    (time, hru) float64 ...
    pptrate    (time, hru) float64 ...
    spechum    (time, hru) float64 ...
    airpres    (time, hru) float64 ...
    windspd    (time, hru) float64 ...
    datastep   float64 ...
    latitude   (hru) float64 ...
    longitude  (hru) float64 ...
    hruID      (hru) float64 ...
    hruId      (hru) float64 ...
    data_step  float64 ...

In [10]:
forcing.hruId

<xarray.DataArray 'hruId' (hru: 1)>
array([1001.])
Dimensions without coordinates: hru

In [11]:
forcing.hruID

<xarray.DataArray 'hruID' (hru: 1)>
array([9.96921e+36])
Dimensions without coordinates: hru

In [12]:
forcing.latitude

<xarray.DataArray 'latitude' (hru: 1)>
array([40.0329])
Dimensions without coordinates: hru

In [13]:
forcing.longitude

<xarray.DataArray 'longitude' (hru: 1)>
array([-105.5464])
Dimensions without coordinates: hru

In [27]:
forcing.time

<xarray.DataArray 'time' (time: 8784)>
array(['2015-10-01T00:00:00.000000000', '2015-10-01T01:00:00.000000000',
       '2015-10-01T02:00:00.000000000', ..., '2016-09-30T21:00:00.000000000',
       '2016-09-30T22:00:00.000000000', '2016-09-30T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2015-10-01 ... 2016-09-30T23:00:00

### ADDED THE CORRECT TIME TO THE decisions.txt file in the summa_setup/settings directory 

### Investigating Other Files for Potential Changes to match the Niwot Site

In [23]:
init_c = xr.open_dataset('/home/jovyan/work/cewa564_project/niwot/summa_setup/params/initial_conditions.nc')
init_c

<xarray.Dataset>
Dimensions:               (hru: 1, ifcToto: 10, midSoil: 9, midToto: 9, scalarv: 1)
Dimensions without coordinates: hru, ifcToto, midSoil, midToto, scalarv
Data variables:
    scalarSnowAlbedo      (scalarv, hru) float64 ...
    scalarSfcMeltPond     (scalarv, hru) float64 ...
    scalarCanairTemp      (scalarv, hru) float64 ...
    dt_init               (scalarv, hru) float64 ...
    mLayerTemp            (midToto, hru) float64 ...
    mLayerVolFracLiq      (midToto, hru) float64 ...
    mLayerVolFracIce      (midToto, hru) float64 ...
    scalarSnowDepth       (scalarv, hru) float64 ...
    nSoil                 (scalarv, hru) int64 ...
    mLayerDepth           (midToto, hru) float64 ...
    scalarCanopyTemp      (scalarv, hru) float64 ...
    mLayerMatricHead      (midSoil, hru) float64 ...
    scalarCanopyIce       (scalarv, hru) float64 ...
    scalarSWE             (scalarv, hru) float64 ...
    nSnow                 (scalarv, hru) int64 ...
    iLayerHeight    